import { detailedBioQuestContent } from "./bioquest-data";

export type MechanicKind = "system" | "flow" | "sequence" | "population" | "network" | "organ" | "cycle" | "energy" | "orbit";

export type ActivityTopic = {
  id: number;
  title: string;
  category: string;
  module: "biosim" | "bioquest" | "biochallenge" | "biostory" | "biolab";
};

export type ScientificSource = {
  label: string;
  url: string;
};

export const scientificSources: Record<string, ScientificSource> = {
  cell: { label: "NCBI Bookshelf · The Cell", url: "https://www.ncbi.nlm.nih.gov/books/NBK9839/" },
  molecular: { label: "NCBI Bookshelf · Molecular Biology of the Cell", url: "https://www.ncbi.nlm.nih.gov/books/NBK21054/" },
  evolution: { label: "Smithsonian Human Origins · Evolution", url: "https://humanorigins.si.edu/education/introduction-human-evolution" },
  ecology: { label: "NASA Earth Observatory · Ecossistemas", url: "https://earthobservatory.nasa.gov/features/CarbonCycle" },
  physiology: { label: "NCBI Bookshelf · Human Physiology", url: "https://www.ncbi.nlm.nih.gov/books/NBK538143/" },
  microbiology: { label: "CDC · Microbiologia e resistência", url: "https://www.cdc.gov/antimicrobial-resistance/about/index.html" },
  plant: { label: "NCBI Bookshelf · Plant Development", url: "https://www.ncbi.nlm.nih.gov/books/NBK26922/" },
  chemistry: { label: "NCBI Bookshelf · Catalysis and Energy", url: "https://www.ncbi.nlm.nih.gov/books/NBK26838/" },
  earth: { label: "USGS · Dynamic Earth", url: "https://www.usgs.gov/science/science-explorer/natural-hazards/how-the-earth-moves" },
  nasa: { label: "NASA Science · Earth and Moon", url: "https://science.nasa.gov/earth/" },
  immunity: { label: "NIH · Immune System", url: "https://www.niaid.nih.gov/research/immune-system-overview" },
  genetics: { label: "NIH · Genome Research", url: "https://www.genome.gov/about-genomics/fact-sheets" },
  hiv: { label: "NIH · HIV Life Cycle", url: "https://hivinfo.nih.gov/understanding-hiv/fact-sheets/hiv-life-cycle" },
  inquiry: { label: "National Academies · Science Investigation", url: "https://nap.nationalacademies.org/resource/25216/interactive/2/" },
};

export type SimContent = {
  mechanic: MechanicKind;
  phenomenon: string;
  question: string;
  controlA: string;
  controlB: string;
  output: string;
  concept: string;
  misconception: string;
  source: ScientificSource;
};

type SimRow = [string, MechanicKind, string, string, string, string, string, string, string, string];

const simRows: SimRow[] = [
  ["Cidade celular", "system", "Uma célula distribui tarefas entre organelas que trocam matéria e informação.", "Como a demanda por proteínas altera a cooperação entre núcleo, ribossomos, retículo e Golgi?", "Demanda por proteínas", "ATP disponível", "Coordenação das organelas", "Organelas não trabalham isoladas: a função celular emerge de fluxos coordenados de informação, matéria e energia.", "A célula não é uma cidade literal nem cada organela tem uma única função rígida.", "cell"],
  ["Transporte pela membrana", "flow", "A bicamada lipídica é seletivamente permeável e proteínas transportadoras ampliam essa seletividade.", "Quando uma substância atravessa diretamente a membrana e quando precisa de uma proteína?", "Gradiente de concentração", "Permeabilidade da membrana", "Fluxo através da membrana", "Moléculas pequenas apolares difundem com mais facilidade; íons e moléculas polares dependem de canais ou transportadores.", "A membrana não escolhe conscientemente o que entra e não é uma parede impermeável.", "cell"],
  ["Difusão", "flow", "Partículas em movimento térmico espalham-se e o fluxo líquido ocorre a favor do gradiente.", "Como a diferença de concentração e a temperatura mudam a velocidade de difusão?", "Diferença de concentração", "Temperatura", "Taxa de difusão", "A difusão resulta do movimento aleatório, com fluxo líquido da maior para a menor concentração até o equilíbrio dinâmico.", "No equilíbrio, as partículas não param; apenas deixa de existir fluxo líquido.", "cell"],
  ["Osmose", "flow", "Água cruza uma membrana semipermeável em resposta à diferença de solutos não permeáveis.", "O que acontece ao volume celular quando o meio externo fica mais concentrado?", "Soluto fora da célula", "Soluto dentro da célula", "Variação do volume celular", "A água se desloca em direção ao compartimento com maior concentração efetiva de solutos não permeáveis.", "O soluto não 'puxa' água como uma corda; o efeito decorre do potencial químico da água.", "cell"],
  ["Bomba de sódio e potássio", "energy", "A Na⁺/K⁺-ATPase usa ATP para manter gradientes iônicos através da membrana.", "Como a disponibilidade de ATP e o vazamento de íons afetam o gradiente mantido pela bomba?", "ATP disponível", "Vazamento de íons", "Gradiente Na⁺/K⁺", "A cada ciclo, a bomba transporta tipicamente três Na⁺ para fora e dois K⁺ para dentro, contribuindo para os gradientes eletroquímicos.", "A bomba não produz sozinha todo o potencial de membrana; canais de vazamento também são decisivos.", "cell"],
  ["Microscópio virtual", "system", "Aumento e resolução são propriedades diferentes de um sistema óptico.", "Por que aumentar demais uma imagem sem melhorar a resolução não revela novos detalhes?", "Aumento", "Abertura numérica", "Detalhe resolvido", "A resolução depende do comprimento de onda e da abertura numérica; aumento vazio apenas amplia borrões.", "Mais aumento não significa automaticamente mais resolução.", "cell"],
  ["História de uma célula", "sequence", "Uma célula passa por crescimento, especialização, divisão e, em alguns tecidos, morte programada.", "Como sinais internos e externos mudam o destino de uma célula ao longo do tempo?", "Sinal de crescimento", "Dano acumulado", "Probabilidade de progressão", "O destino celular depende de expressão gênica, ambiente, checkpoints e sinais de sobrevivência ou diferenciação.", "Todas as células de um organismo não percorrem o mesmo ciclo nem se dividem continuamente.", "cell"],
  ["Construindo um DNA", "sequence", "Duas fitas antiparalelas pareiam bases complementares e formam uma dupla hélice.", "Que regras permitem reconstruir a fita complementar de uma sequência de DNA?", "Proporção A–T", "Proporção G–C", "Pareamentos corretos", "A pareia com T e G com C por pontes de hidrogênio; o esqueleto açúcar-fosfato dá direção às fitas.", "DNA não é uma escada plana e as pontes de hidrogênio não unem o esqueleto da molécula.", "molecular"],
  ["Replicação do DNA", "sequence", "A replicação é semiconservativa e ocorre por síntese 5'→3' em forquilhas de replicação.", "Como a velocidade da helicase e a ação da DNA polimerase afetam a fidelidade da cópia?", "Abertura da forquilha", "Revisão da polimerase", "DNA copiado corretamente", "Cada molécula-filha conserva uma fita antiga; a síntese contínua e descontínua decorre do antiparalelismo.", "A DNA polimerase não inicia uma fita do zero e não sintetiza no sentido 3'→5'.", "molecular"],
  ["Mutações", "population", "Alterações na sequência podem ser neutras, prejudiciais ou vantajosas conforme o contexto.", "Como a taxa de mutação e a pressão seletiva alteram a frequência de uma variante?", "Taxa de mutação", "Pressão seletiva", "Frequência da variante", "Mutações criam variação ao acaso em relação à necessidade; seleção e deriva mudam sua frequência depois.", "Organismos não produzem a mutação de que precisam.", "genetics"],
  ["Tradução de proteínas", "sequence", "Ribossomos leem códons do mRNA e tRNAs entregam aminoácidos para formar um polipeptídeo.", "O que muda quando a disponibilidade de tRNA e a integridade do mRNA variam?", "tRNA carregado", "Integridade do mRNA", "Proteína sintetizada", "A sequência de códons determina a ordem de aminoácidos entre início e parada; o ribossomo catalisa a ligação peptídica.", "Um gene não vira diretamente proteína: transcrição, processamento e tradução são etapas distintas.", "molecular"],
  ["Viagem de um gene até uma proteína", "flow", "A informação de um gene é transcrita, processada, exportada e traduzida.", "Em qual etapa uma falha impede que a informação do DNA se torne proteína funcional?", "Transcrição do gene", "Eficiência de tradução", "Proteína funcional", "Expressão gênica conecta DNA, RNA e proteína, mas é regulada em várias etapas e não é um caminho inevitável.", "O dogma central não afirma que todo DNA produz uma proteína o tempo todo.", "molecular"],
  ["Seleção natural", "population", "Indivíduos variam e algumas diferenças herdáveis alteram o sucesso reprodutivo em certo ambiente.", "Como a vantagem reprodutiva e a herdabilidade mudam a composição de uma população?", "Vantagem reprodutiva", "Herdabilidade do traço", "Frequência do traço", "Seleção natural muda frequências de variantes herdáveis ao longo das gerações; populações evoluem, indivíduos não.", "Seleção não busca perfeição nem antecipa necessidades futuras.", "evolution"],
  ["Deriva genética", "population", "A amostragem aleatória de alelos entre gerações pode alterar frequências, sobretudo em populações pequenas.", "Por que a mesma variante oscila mais em uma população pequena?", "Tamanho populacional", "Número de gerações", "Oscilação aleatória", "Deriva genética é mudança aleatória de frequências alélicas e pode fixar ou eliminar variantes sem vantagem adaptativa.", "Toda mudança evolutiva não é causada por seleção natural.", "evolution"],
  ["Seleção sexual", "population", "Traços que aumentam acesso a parceiros podem evoluir mesmo com custos de sobrevivência.", "Como preferência de parceiros e custo energético afetam a frequência de um ornamento?", "Preferência de parceiros", "Custo do ornamento", "Sucesso reprodutivo", "A seleção sexual resulta de competição e escolha de parceiros e pode favorecer dimorfismos.", "O traço mais chamativo não é necessariamente o melhor para sobreviver.", "evolution"],
  ["Máquina do tempo evolutiva", "population", "Linhas evolutivas acumulam mudanças, se ramificam e podem se extinguir.", "Como tempo, isolamento e mudança ambiental transformam uma população ancestral?", "Tempo de isolamento", "Mudança ambiental", "Divergência acumulada", "Ancestralidade comum forma uma árvore ramificada; espécies atuais não são degraus de uma escada de progresso.", "Evolução não tem meta nem coloca espécies atuais como ancestrais diretas umas das outras.", "evolution"],
  ["Caminhando entre os dinossauros", "population", "Dinossauros ocuparam muitos nichos e aves são o ramo sobrevivente dos dinossauros terópodes.", "Como clima e disponibilidade de alimento mudam quais estratégias corporais prosperam?", "Oferta de alimento", "Variação climática", "Sobrevivência do grupo", "Fósseis e relações anatômicas permitem reconstruir ecossistemas sem transformar a reconstrução em fotografia exata.", "Nem todos os dinossauros viveram juntos e sua extinção não foi instantânea em todo o planeta.", "evolution"],
  ["Ilha ecológica", "network", "Colonização, extinção e área determinam a riqueza de espécies em ilhas.", "Como distância do continente e tamanho da ilha afetam a diversidade?", "Distância da fonte", "Área da ilha", "Riqueza de espécies", "Ilhas maiores tendem a sustentar mais espécies; ilhas próximas recebem mais colonizadores, com muitas exceções ecológicas.", "Uma ilha não é um sistema fechado nem a relação espécie-área prevê números exatos sozinha.", "ecology"],
  ["Teia alimentar dinâmica", "network", "Espécies estão ligadas por múltiplas relações de consumo e energia diminui entre níveis tróficos.", "O que acontece à rede quando um consumidor-chave diminui?", "População de produtores", "Pressão de predação", "Estabilidade da teia", "Teias alimentares representam múltiplos caminhos de matéria e energia; remover uma espécie pode gerar cascatas indiretas.", "Cadeias alimentares reais raramente são linhas simples.", "ecology"],
  ["Sucessão ecológica", "sequence", "Comunidades mudam após perturbações conforme organismos modificam e respondem ao ambiente.", "Como intensidade da perturbação e chegada de propágulos alteram a recuperação?", "Intensidade da perturbação", "Chegada de espécies", "Recuperação da comunidade", "Sucessão é contingente: facilitação, tolerância e inibição podem operar e não há um clímax universal imutável.", "A sucessão não segue sempre a mesma lista ordenada de espécies.", "ecology"],
  ["Ecossistema vivo", "network", "Fluxos de energia conectam produtores, consumidores e decompositores; nutrientes circulam.", "Como produtividade e decomposição afetam o funcionamento do ecossistema?", "Produtividade primária", "Taxa de decomposição", "Matéria reciclada", "Energia flui e se dissipa como calor, enquanto elementos químicos circulam entre componentes bióticos e abióticos.", "Energia não é reciclada no ecossistema da mesma forma que a matéria.", "ecology"],
  ["Polinização", "network", "Pólen precisa alcançar estruturas reprodutivas compatíveis por vento, água ou animais.", "Como visitas de polinizadores e fragmentação do habitat afetam a produção de sementes?", "Visitas de polinizadores", "Fragmentação do habitat", "Fecundação bem-sucedida", "Polinização é transferência de pólen; fecundação ocorre depois, se houver compatibilidade e germinação do tubo polínico.", "Polinização e fecundação não são o mesmo processo.", "ecology"],
  ["Ciclo do carbono", "cycle", "Carbono circula entre atmosfera, organismos, oceanos e rochas em escalas muito diferentes.", "Como fotossíntese e combustão alteram temporariamente o carbono atmosférico?", "Fixação fotossintética", "Emissões por combustão", "Carbono atmosférico relativo", "Fotossíntese remove CO₂ do ar; respiração, decomposição e combustão o devolvem, enquanto reservatórios geológicos operam lentamente.", "O ciclo natural não anula um acréscimo rápido de carbono fóssil.", "ecology"],
  ["Ciclo da água", "cycle", "Energia solar e gravidade movimentam água por evaporação, condensação, precipitação, infiltração e escoamento.", "Como temperatura e cobertura vegetal alteram os caminhos da água?", "Temperatura da superfície", "Cobertura vegetal", "Água na atmosfera", "O ciclo hidrológico tem múltiplos trajetos e reservatórios; transpiração vegetal é parte importante do fluxo continental.", "A água não percorre um único círculo ordenado nem toda chuva vem diretamente do oceano.", "nasa"],
  ["Coração", "organ", "Pressões geradas pelo miocárdio e válvulas direcionam o sangue em dois circuitos.", "Como frequência cardíaca e volume sistólico afetam o débito cardíaco?", "Frequência cardíaca", "Volume por batimento", "Débito cardíaco", "Débito cardíaco é o produto entre frequência e volume sistólico, ajustado às demandas e limitado pelo enchimento e pela função cardíaca.", "O lado esquerdo não bombeia sangue 'mais rápido'; ele gera maior pressão para o circuito sistêmico.", "physiology"],
  ["Hormônios", "network", "Hormônios viajam pelo corpo, mas apenas células com receptores adequados respondem.", "Como concentração do sinal e quantidade de receptores afetam a resposta?", "Concentração hormonal", "Receptores disponíveis", "Resposta da célula-alvo", "Sinalização endócrina depende de receptores, transdução e retroalimentação; mais hormônio nem sempre produz resposta ilimitada.", "Hormônios não agem em todas as células nem são classificados apenas por emoção ou sexo.", "physiology"],
  ["Potencial de ação", "organ", "Canais voltagem-dependentes produzem uma mudança regenerativa do potencial da membrana neuronal.", "Como estímulo e período refratário determinam se um impulso ocorre?", "Intensidade do estímulo", "Recuperação dos canais", "Probabilidade de disparo", "Acima do limiar, o potencial de ação é tudo-ou-nada; intensidade é codificada principalmente pela frequência de disparos.", "Um estímulo mais forte não torna cada potencial de ação maior.", "physiology"],
  ["Sistema imunológico", "network", "Barreiras, resposta inata e resposta adaptativa cooperam para reconhecer e controlar ameaças.", "Como carga do patógeno e memória imunológica alteram o tempo de resposta?", "Carga do patógeno", "Memória imunológica", "Controle da infecção", "A imunidade adaptativa gera especificidade e memória, enquanto mecanismos inatos respondem rapidamente e orientam a resposta.", "O sistema imune não é um exército infalível e inflamação não é sempre doença.", "immunity"],
  ["Digestão completa", "flow", "Alimentos são fragmentados, hidrolisados e seus nutrientes absorvidos ao longo do tubo digestório.", "Como atividade enzimática e área de absorção afetam o aproveitamento de nutrientes?", "Atividade enzimática", "Área das vilosidades", "Nutrientes absorvidos", "Digestão mecânica e química preparam moléculas para absorção; fígado, pâncreas e microbiota participam do processamento.", "O estômago não realiza sozinho toda a digestão e alimentos não seguem para o fígado como pedaços.", "physiology"],
  ["História de um glóbulo vermelho", "flow", "Hemácias circulam entre pulmões e tecidos transportando O₂ ligado reversivelmente à hemoglobina.", "Como oxigênio alveolar e demanda dos tecidos afetam a saturação da hemoglobina?", "O₂ nos alvéolos", "Demanda dos tecidos", "O₂ entregue aos tecidos", "Hemoglobina carrega a maior parte do O₂; gradientes de pressão parcial favorecem carga nos pulmões e descarga nos tecidos.", "Hemácias não carregam bolhas de oxigênio nem consomem o O₂ que transportam por mitocôndrias.", "physiology"],
  ["Visão", "organ", "Córnea e cristalino focalizam luz; fotorreceptores convertem fótons em sinais neurais.", "Como distância do objeto e acomodação do cristalino afetam o foco na retina?", "Distância do objeto", "Acomodação do cristalino", "Nitidez na retina", "A imagem retinal é processada por circuitos da retina e do cérebro; cones e bastonetes têm sensibilidades diferentes.", "O cérebro não recebe uma fotografia pronta nem há visão apenas no olho.", "physiology"],
  ["Audição", "organ", "Ondas sonoras movem tímpano e ossículos; a cóclea separa frequências e converte vibração em sinal neural.", "Como frequência e amplitude alteram a região ativada e a intensidade percebida?", "Frequência do som", "Amplitude da onda", "Resposta coclear", "A membrana basilar é tonotópica: diferentes frequências atingem máximos em regiões distintas; intensidade envolve amplitude e recrutamento neural.", "Som agudo não é necessariamente alto; altura e intensidade são dimensões diferentes.", "physiology"],
  ["Olfato", "organ", "Moléculas voláteis ativam combinações de receptores no epitélio olfatório.", "Como concentração do odorante e adaptação mudam a percepção?", "Concentração do odorante", "Tempo de exposição", "Intensidade percebida", "O cérebro reconhece padrões combinatórios de receptores; adaptação reduz a resposta a estímulos contínuos.", "Cada cheiro não corresponde a um único receptor exclusivo.", "physiology"],
  ["Paladar", "organ", "Células gustativas detectam qualidades básicas e o cérebro integra gosto, olfato e textura.", "Como concentração do soluto e contribuição do olfato mudam o sabor percebido?", "Concentração gustativa", "Contribuição olfativa", "Intensidade do sabor", "Gosto e olfato retronasal cooperam na percepção de sabor; receptores não ficam em zonas rígidas da língua.", "O mapa clássico da língua com regiões exclusivas é incorreto.", "physiology"],
  ["Ossos", "system", "Tecido ósseo é vivo, vascularizado e remodelado por osteoblastos e osteoclastos.", "Como carga mecânica e disponibilidade mineral afetam a remodelação?", "Carga mecânica", "Oferta de cálcio e fosfato", "Balanço de remodelação", "Osso combina matriz colágena e mineral; remodelação responde a forças, hormônios e metabolismo.", "Ossos não são estruturas mortas nem simples depósitos inertes de cálcio.", "physiology"],
  ["Músculos", "organ", "Filamentos de actina e miosina deslizam quando Ca²⁺ permite ciclos de pontes cruzadas alimentados por ATP.", "Como cálcio citosólico e ATP alteram a força de contração?", "Ca²⁺ disponível", "ATP disponível", "Força de contração", "A fibra encurta porque sarcômeros encurtam; os filamentos não diminuem de tamanho.", "ATP é necessário tanto para o ciclo de força quanto para o relaxamento muscular.", "physiology"],
  ["Desenvolvimento embrionário", "sequence", "Divisões, movimentos celulares e sinais posicionais transformam o zigoto em tecidos e órgãos.", "Como proliferação e sinalização alteram a formação de padrões no embrião?", "Taxa de proliferação", "Precisão dos sinais", "Organização dos tecidos", "Diferenciação muda expressão gênica, não o conjunto básico de DNA; gastrulação estabelece camadas germinativas.", "O embrião não cresce apenas aumentando de tamanho como uma miniatura pronta.", "physiology"],
  ["Decisões do cérebro", "network", "Decisões emergem da integração de evidências, memória, valor esperado e estado corporal.", "Como força da evidência e urgência alteram uma escolha?", "Força da evidência", "Pressão de tempo", "Confiança da decisão", "Redes neurais acumulam informação até limiares variáveis; emoção e razão não são sistemas totalmente separados.", "Não existe um único 'centro da decisão' que comanda sozinho o cérebro.", "physiology"],
  ["Fotossíntese", "energy", "Cloroplastos convertem energia luminosa em energia química e usam carbono para formar moléculas orgânicas.", "Como intensidade luminosa e CO₂ alteram a taxa até surgirem fatores limitantes?", "Intensidade luminosa", "CO₂ disponível", "Taxa fotossintética", "Reações luminosas geram ATP e NADPH; o ciclo de Calvin fixa CO₂. A taxa satura quando outro fator limita.", "Plantas não obtêm alimento do solo e também realizam respiração celular.", "plant"],
  ["Germinação de sementes", "sequence", "A embebição reativa metabolismo; reservas sustentam o embrião até a plântula fotossintetizar.", "Como água e temperatura influenciam a germinação de uma semente viável?", "Disponibilidade de água", "Temperatura adequada", "Sementes germinadas", "Água, temperatura e, em algumas espécies, luz ou quebra de dormência controlam a germinação; oxigênio sustenta respiração.", "Solo e luz não são requisitos universais para o início da germinação.", "plant"],
  ["Ligações químicas", "system", "Átomos interagem por redistribuição de elétrons, formando ligações com polaridades e energias distintas.", "Como diferença de eletronegatividade e geometria alteram a polaridade molecular?", "Diferença de eletronegatividade", "Assimetria molecular", "Polaridade resultante", "Ligação iônica e covalente são modelos de distribuição eletrônica; a geometria determina se dipolos se somam ou se cancelam.", "Uma ligação polar não torna automaticamente toda a molécula polar.", "chemistry"],
  ["pH", "system", "pH expressa logaritmicamente a atividade aproximada de H⁺ em solução.", "Como quantidade de ácido e capacidade tampão mudam o pH?", "Ácido adicionado", "Capacidade do tampão", "pH da solução", "Uma unidade de pH representa mudança de dez vezes em H⁺; tampões resistem a variações dentro de uma faixa.", "pH 4 não é apenas duas vezes mais ácido que pH 8.", "chemistry"],
  ["Catalisadores e enzimas", "energy", "Catalisadores aceleram reações ao reduzir a barreira de ativação sem alterar o equilíbrio final.", "Como temperatura e concentração de substrato afetam a velocidade enzimática?", "Concentração de substrato", "Temperatura relativa ao ótimo", "Velocidade da reação", "Enzimas saturam quando sítios ativos estão ocupados e podem perder estrutura em condições extremas.", "Enzimas não fornecem energia à reação e não são consumidas a cada ciclo.", "chemistry"],
  ["Estados físicos da matéria", "cycle", "O estado depende do balanço entre energia cinética e forças entre partículas.", "Como temperatura e pressão deslocam uma substância entre sólido, líquido e gás?", "Temperatura", "Pressão", "Estado predominante", "Mudanças de fase reorganizam partículas sem mudar sua identidade química e envolvem transferência de energia latente.", "Durante uma mudança de fase de substância pura, calor adicionado não implica aumento imediato de temperatura.", "chemistry"],
  ["Fluxo de calor", "flow", "Energia térmica flui espontaneamente do corpo de maior para o de menor temperatura.", "Como diferença de temperatura e isolamento alteram a taxa de transferência?", "Diferença de temperatura", "Isolamento térmico", "Taxa de fluxo de calor", "Condução, convecção e radiação transferem energia por mecanismos diferentes até o equilíbrio térmico.", "Frio não flui como uma substância; o que se transfere é energia.", "chemistry"],
  ["Conservação da energia", "energy", "Energia muda de forma e se dispersa, mas não é criada nem destruída em um sistema fechado.", "Como atrito e energia inicial mudam a parcela útil de uma transformação?", "Energia inicial", "Atrito", "Energia útil", "A energia total se conserva, embora energia mecânica possa virar energia térmica menos disponível para trabalho.", "Dizer que energia foi 'perdida' geralmente significa que se dispersou, não que deixou de existir.", "chemistry"],
  ["Funcionamento de uma pilha", "flow", "Reações de oxidação e redução separadas impulsionam elétrons por um circuito externo.", "Como diferença de potencial e resistência alteram a corrente?", "Diferença de potencial", "Resistência do circuito", "Corrente elétrica", "Elétrons percorrem o circuito externo; íons no eletrólito mantêm a neutralidade e fecham o circuito.", "Elétrons não atravessam a ponte salina da mesma forma que no fio.", "chemistry"],
  ["Radioatividade", "population", "Núcleos instáveis decaem probabilisticamente com meia-vida característica.", "Como número inicial de núcleos e tempo transcorrido afetam a atividade?", "Núcleos instáveis iniciais", "Tempo em meias-vidas", "Núcleos restantes", "A meia-vida descreve uma população; não permite prever quando um núcleo individual decairá.", "Depois de uma meia-vida não desaparece toda a amostra.", "chemistry"],
  ["Placas tectônicas", "flow", "Placas litosféricas movem-se sobre o manto e interagem em limites divergentes, convergentes e transformantes.", "Como direção do movimento e densidade das placas determinam o tipo de limite?", "Velocidade relativa", "Contraste de densidade", "Deformação da crosta", "Subducção, expansão oceânica e falhas transformantes explicam padrões de vulcões, fossas e terremotos.", "Continentes não flutuam isoladamente sobre magma líquido.", "earth"],
  ["Erosão", "flow", "Água, vento, gelo e gravidade removem e transportam sedimentos.", "Como cobertura vegetal e intensidade da chuva alteram a perda de solo?", "Intensidade da chuva", "Cobertura vegetal", "Sedimento transportado", "Erosão transporta material; intemperismo o desagrega no local e deposição ocorre quando a energia do agente diminui.", "Intemperismo e erosão não são sinônimos.", "earth"],
  ["Formação da chuva", "cycle", "Ar úmido ascende, esfria e o vapor condensa em partículas, formando gotas ou cristais.", "Como umidade e resfriamento do ar afetam a chance de precipitação?", "Umidade do ar", "Resfriamento na ascensão", "Água condensada", "Nuvens exigem saturação e núcleos de condensação; precipitação ocorre quando partículas crescem e vencem correntes ascendentes.", "Nuvens não são vapor invisível nem toda nuvem produz chuva.", "nasa"],
  ["Tornados", "flow", "Rotação intensa pode se organizar em tempestades com forte cisalhamento do vento.", "Como instabilidade atmosférica e cisalhamento alteram o potencial de rotação?", "Instabilidade do ar", "Cisalhamento do vento", "Potencial de rotação", "Supercélulas podem inclinar e intensificar rotação, mas condições favoráveis não garantem a formação de um tornado.", "Tornados não surgem simplesmente do encontro de qualquer ar quente com ar frio.", "nasa"],
  ["Vulcões", "flow", "Magma sobe quando sua flutuabilidade e pressão superam a resistência das rochas.", "Como viscosidade do magma e conteúdo de gases alteram o estilo eruptivo?", "Viscosidade do magma", "Gases dissolvidos", "Explosividade relativa", "Magmas viscosos retêm gases e podem favorecer erupções explosivas; magmas fluidos tendem a extravasar mais facilmente.", "Todo vulcão não é um cone explosivo alimentado por uma câmara universal de magma.", "earth"],
  ["Campo magnético terrestre", "flow", "Movimentos de metal líquido condutor no núcleo externo sustentam o geodínamo.", "Como movimento do fluido e rotação alteram a organização do campo?", "Convecção no núcleo", "Organização rotacional", "Intensidade do campo", "O campo varia no tempo, possui componentes não dipolares e pode inverter sua polaridade sem desaparecer instantaneamente.", "O polo magnético não coincide sempre com o polo geográfico.", "earth"],
  ["Estações do ano", "orbit", "A inclinação do eixo terrestre muda o ângulo solar e a duração do dia durante a órbita.", "Como latitude e posição orbital alteram a energia solar recebida?", "Latitude", "Inclinação em direção ao Sol", "Energia diária recebida", "Estações resultam principalmente da inclinação axial, com padrões opostos nos hemisférios.", "Verão não ocorre porque a Terra está globalmente mais perto do Sol.", "nasa"],
  ["Fases da Lua, eclipses e marés", "orbit", "A geometria Sol–Terra–Lua controla a fração iluminada visível, alinhamentos de eclipse e forças de maré.", "Como posição orbital e alinhamento mudam o fenômeno observado?", "Posição da Lua", "Alinhamento orbital", "Iluminação e maré", "Fases não são sombras da Terra; eclipses exigem alinhamento próximo dos nós e marés combinam gravidade lunar e solar.", "Não ocorre eclipse todo mês porque a órbita lunar é inclinada.", "nasa"],
  ["Construção de um planeta (clima)", "system", "Clima planetário depende de energia estelar, albedo, atmosfera, rotação e distribuição de continentes.", "Como efeito estufa e refletividade alteram a temperatura de equilíbrio?", "Gases de efeito estufa", "Albedo planetário", "Temperatura média relativa", "Atmosferas absorvem e redistribuem energia; feedbacks de gelo, vapor e nuvens podem amplificar ou reduzir mudanças.", "Clima não é determinado por um único gás nem equivale ao tempo de um dia.", "nasa"],
  ["Construa um cromossomo", "sequence", "DNA associa-se a histonas e forma níveis dinâmicos de compactação.", "Como comprimento do DNA e grau de compactação alteram o espaço ocupado?", "Comprimento de DNA", "Compactação da cromatina", "Organização cromossômica", "Cromossomos são cromatina organizada; sua forma condensada é mais visível durante a divisão.", "Cromossomos não têm sempre a forma de X e um X duplicado ainda conta como um cromossomo.", "molecular"],
  ["Mitose em câmera lenta", "sequence", "Cromossomos duplicados condensam, alinham-se, separam-se e dois núcleos se reorganizam.", "Como ligação ao fuso e progressão temporal alteram a distribuição dos cromossomos?", "Ligação ao fuso", "Progressão da mitose", "Distribuição correta", "A mitose separa cromátides-irmãs; a duplicação do DNA ocorreu antes, na fase S.", "Interfase não é repouso e replicação do DNA não acontece durante a mitose.", "molecular"],
  ["O que acontece se o fuso falhar?", "system", "Microtúbulos do fuso conectam cinetócoros e geram forças para separar cromossomos.", "Como falhas de ligação e atividade do checkpoint afetam a segregação?", "Ligações incorretas", "Força do checkpoint", "Segregação correta", "O checkpoint do fuso adia a anáfase até que cromossomos estejam adequadamente ligados; falhas podem gerar aneuploidia.", "O fuso não empurra cromossomos apenas a partir dos polos; há múltiplas forças e ligações.", "molecular"],
  ["Corrida dos cromossomos", "sequence", "Cromossomos não competem; motores moleculares e dinâmica de microtúbulos coordenam seus movimentos.", "Como estabilidade dos microtúbulos e sincronização alteram a chegada aos polos?", "Dinâmica dos microtúbulos", "Sincronização do checkpoint", "Separação sincronizada", "A metáfora de corrida serve para observar tempos, mas a célula prioriza coordenação e fidelidade, não velocidade máxima.", "Cromossomos não têm intenção nem se movem por conta própria.", "molecular"],
  ["Separando cromátides", "sequence", "A coesina que mantém cromátides unidas é clivada no início da anáfase.", "Como ativação da separase e tensão do fuso mudam a separação?", "Ativação da separase", "Tensão bipolar", "Cromátides separadas", "A transição para anáfase é regulada; coesinas são removidas e cada cromátide torna-se um cromossomo-filho.", "Cromátides não são cromossomos homólogos.", "molecular"],
  ["Divisão de célula animal × vegetal", "sequence", "Células animais formam sulco de clivagem; vegetais constroem uma placa celular entre as filhas.", "Como presença de parede e entrega de vesículas mudam a citocinese?", "Rigidez da parede", "Entrega de vesículas", "Conclusão da citocinese", "A parede impede estrangulamento; vesículas do Golgi formam a placa e a nova parede vegetal.", "Mitose nuclear é muito semelhante; a principal diferença aqui está na citocinese.", "cell"],
  ["Câncer", "population", "Células com alterações em controle de proliferação, morte e reparo podem ser selecionadas dentro do tecido.", "Como taxa de divisão e eficácia dos checkpoints afetam a expansão clonal?", "Sinais proliferativos", "Eficácia dos checkpoints", "Expansão de células alteradas", "Câncer é evolução somática multietapas, com diversidade entre tumores e interação com o microambiente.", "Câncer não é uma única doença nem resulta de uma única mutação universal.", "molecular"],
  ["Checkpoints celulares", "system", "Redes de controle verificam tamanho, nutrientes, DNA e ligação ao fuso antes de transições irreversíveis.", "Como dano no DNA e rigor do checkpoint alteram a progressão?", "Dano detectado", "Rigor do checkpoint", "Progressão segura", "Checkpoints integram sinais; podem pausar o ciclo, promover reparo, senescência ou morte celular.", "Checkpoint não é um fiscal consciente nem garante erro zero.", "molecular"],
  ["Danos no DNA", "system", "Radiação, químicos e erros metabólicos lesionam DNA, que é monitorado por diferentes vias de reparo.", "Como quantidade de dano e capacidade de reparo afetam mutações restantes?", "Dano inicial", "Capacidade de reparo", "Integridade do genoma", "Tipos distintos de lesão exigem mecanismos distintos; dano não reparado pode causar mutação ou bloquear replicação.", "Reparo não restaura sempre perfeitamente o DNA e mutação não é sinônimo de dano físico.", "molecular"],
  ["A vida inteira de uma célula", "sequence", "Nascimento, crescimento, função, divisão, senescência e morte variam conforme o tipo celular.", "Como sinais de sobrevivência e dano acumulado mudam o destino?", "Sinais de sobrevivência", "Dano acumulado", "Tempo de vida funcional", "Algumas células se renovam rapidamente; outras permanecem diferenciadas por anos. Homeostase equilibra produção e perda.", "Todas as células do corpo não são substituídas a cada sete anos.", "cell"],
  ["Meiose como quebra-cabeça", "sequence", "Uma replicação do DNA é seguida por duas divisões que separam homólogos e depois cromátides.", "Como pareamento de homólogos e duas divisões reduzem a ploidia?", "Pareamento de homólogos", "Conclusão das divisões", "Gametas haploides", "Meiose I é reducional; meiose II separa cromátides, gerando diversidade por segregação e recombinação.", "Meiose não é simplesmente duas mitoses consecutivas.", "molecular"],
  ["Crossing-over", "sequence", "Cromátides não irmãs de homólogos trocam segmentos durante a prófase I.", "Como número de eventos e distância entre genes alteram combinações alélicas?", "Eventos de recombinação", "Distância entre loci", "Gametas recombinantes", "Recombinação cria novas combinações; genes muito próximos tendem a ser herdados juntos com maior frequência.", "Crossing-over não troca genes inteiros obrigatoriamente nem ocorre entre quaisquer cromossomos.", "genetics"],
  ["Não-disjunção", "sequence", "Falha na separação de homólogos ou cromátides produz gametas com número cromossômico alterado.", "Em qual divisão a falha ocorre e que tipos de gameta aparecem?", "Falha na meiose I", "Falha na meiose II", "Gametas aneuploides", "O padrão de gametas difere conforme a não-disjunção ocorra na primeira ou segunda divisão.", "Aneuploidia não significa necessariamente um conjunto haploide inteiro a mais.", "genetics"],
  ["Zigoto", "sequence", "Fusão de gametas restaura a diploidia e inicia uma nova trajetória de desenvolvimento.", "Como contribuição dos gametas e primeiras clivagens mudam o número de células?", "Fusão dos gametas", "Ritmo de clivagem", "Células embrionárias", "O zigoto é uma única célula diploide; clivagens aumentam o número de células sem grande aumento inicial do volume total.", "Zigoto não é um bebê em miniatura nem um conjunto de muitas células.", "physiology"],
  ["Linhagem celular", "sequence", "Divisões sucessivas conectam células por ancestralidade e decisões de destino.", "Como assimetria de sinais e número de divisões alteram os tipos celulares produzidos?", "Assimetria de sinais", "Número de divisões", "Diversidade de destinos", "Mapas de linhagem rastreiam descendência; células com o mesmo genoma podem adotar destinos distintos por regulação gênica.", "Linhagem celular não significa que cada tecido tenha um DNA diferente.", "molecular"],
  ["Você é uma glicose", "energy", "Os seis carbonos da glicose são reorganizados e oxidados ao longo da glicólise e da respiração.", "Como oxigênio e demanda de ATP alteram o destino do piruvato e dos elétrons?", "Oxigênio disponível", "Demanda de ATP", "Energia capturada", "Glicólise ocorre no citosol; carbono vira piruvato e depois CO₂ na oxidação completa, enquanto elétrons alimentam a cadeia respiratória.", "A glicose não entra inteira na mitocôndria para ser simplesmente 'queimada'.", "molecular"],
  ["Glicólise", "sequence", "Dez reações citosólicas convertem glicose em dois piruvatos, com investimento e retorno de ATP.", "Como disponibilidade de glicose e NAD⁺ afetam o fluxo glicolítico?", "Glicose disponível", "NAD⁺ regenerado", "Piruvato e ATP líquido", "Por glicose, a glicólise produz saldo líquido de dois ATP e dois NADH, além de dois piruvatos.", "Glicólise não requer diretamente oxigênio e não ocorre dentro da mitocôndria.", "molecular"],
  ["Ciclo de Krebs", "cycle", "Acetil-CoA é oxidado no ciclo do ácido cítrico, reduzindo NAD⁺ e FAD e liberando CO₂.", "Como acetil-CoA e disponibilidade de aceptores de elétrons alteram o giro do ciclo?", "Acetil-CoA disponível", "NAD⁺ e FAD oxidados", "Carreadores reduzidos", "O ciclo regenera oxaloacetato e captura principalmente energia em NADH e FADH₂, não em grande quantidade direta de ATP.", "O ciclo de Krebs não é a etapa que produz a maior parte do ATP diretamente.", "molecular"],
  ["Cadeia respiratória", "flow", "Elétrons de NADH e FADH₂ percorrem complexos que bombeiam prótons na membrana mitocondrial interna.", "Como oferta de elétrons e oxigênio alteram o gradiente de prótons?", "NADH e FADH₂", "Oxigênio disponível", "Gradiente de prótons", "O₂ é o aceptor final de elétrons; o bombeamento cria força próton-motriz usada pela ATP sintase.", "Oxigênio não se transforma diretamente em ATP.", "molecular"],
  ["ATP", "energy", "ATP acopla reações exergônicas a processos celulares que exigem energia.", "Como demanda de trabalho e regeneração de ATP alteram o estoque momentâneo?", "Demanda de trabalho celular", "Taxa de regeneração", "ATP disponível", "ATP é continuamente hidrolisado e regenerado; funciona como intermediário de transferência, não como reserva energética de longo prazo.", "ATP não é 'energia pura' nem fica armazenado em grande quantidade por muito tempo.", "molecular"],
  ["Quem produz mais energia?", "energy", "Carboidratos, lipídios e proteínas entram em pontos diferentes do metabolismo e rendem quantidades distintas.", "Como tipo de combustível e disponibilidade de oxigênio alteram o ATP obtido?", "Proporção de lipídios", "Oxigênio disponível", "Rendimento relativo de ATP", "Ácidos graxos muito reduzidos rendem mais ATP por molécula, mas exigem vias e condições diferentes; velocidade e rendimento não são iguais.", "O combustível com maior rendimento não é necessariamente o mais rápido de mobilizar.", "molecular"],
  ["Exercício físico", "energy", "Músculos ajustam fosfocreatina, glicólise, oxidação e fluxo sanguíneo conforme intensidade e duração.", "Como intensidade e oferta de oxigênio mudam a contribuição das vias energéticas?", "Intensidade do exercício", "Oferta de oxigênio", "ATP regenerado", "Todos os sistemas contribuem em proporções variáveis; lactato pode ser reutilizado e não é simples resíduo causador direto da dor tardia.", "Exercício aeróbio e anaeróbio não são interruptores mutuamente exclusivos.", "physiology"],
  ["Fermentação", "energy", "Fermentação regenera NAD⁺ para sustentar a glicólise quando a cadeia respiratória não oxida NADH suficientemente.", "Como disponibilidade de oxigênio e demanda glicolítica alteram a formação de lactato ou etanol?", "Oxigênio disponível", "Demanda glicolítica", "NAD⁺ regenerado", "Fermentação permite continuidade da glicólise, mas o saldo energético permanece em dois ATP por glicose.", "Fermentação não produz a maior parte do ATP e não ocorre apenas em microrganismos.", "molecular"],
  ["Hipóxia", "energy", "Baixa oferta de O₂ limita a fosforilação oxidativa e ativa respostas celulares de adaptação.", "Como oxigênio e demanda energética alteram ATP e lactato?", "Oxigênio disponível", "Demanda energética", "ATP sustentado", "Células aumentam glicólise e respostas mediadas por HIF, mas tecidos de alta demanda podem perder função se a hipóxia persistir.", "Ter oxigênio no ar não garante oferta adequada ao tecido; ventilação, circulação e hemoglobina importam.", "physiology"],
  ["Envenenamento por cianeto", "energy", "Cianeto inibe a citocromo c oxidase e bloqueia a transferência final de elétrons para O₂.", "Como dose do inibidor e demanda de ATP afetam a respiração mitocondrial?", "Inibição do complexo IV", "Demanda de ATP", "Fosforilação oxidativa", "Mesmo com O₂ presente no sangue, células não conseguem usá-lo adequadamente e a produção mitocondrial de ATP colapsa.", "O problema não é falta de oxigênio ambiental, mas bloqueio de sua utilização celular.", "molecular"],
  ["Quantidade de mitocôndrias", "energy", "Células ajustam número e capacidade mitocondrial às demandas energéticas e sinais de treinamento.", "Como densidade mitocondrial e demanda celular alteram a capacidade oxidativa?", "Densidade mitocondrial", "Demanda energética", "Reserva de capacidade", "Tecidos diferem em conteúdo mitocondrial; biogênese e remoção de mitocôndrias mantêm qualidade e capacidade.", "Mais mitocôndrias não significa ATP ilimitado sem combustível, oxigênio e regulação.", "molecular"],
  ["Organelas cooperando", "system", "Núcleo, ribossomos, retículo, Golgi, lisossomos e mitocôndrias trocam produtos e sinais.", "Como síntese proteica e transporte vesicular afetam a entrega de uma proteína secretada?", "Síntese no retículo", "Transporte vesicular", "Proteína entregue", "Proteínas secretadas percorrem uma rota coordenada com endereçamento, modificação e controle de qualidade.", "Organelas não são departamentos totalmente independentes.", "cell"],
  ["Quanto ATP você consegue?", "energy", "O rendimento de ATP varia com combustível, lançadeiras, acoplamento e custos celulares.", "Como oxigênio e acoplamento mitocondrial mudam o rendimento relativo por glicose?", "Oxigênio disponível", "Eficiência de acoplamento", "ATP relativo por glicose", "Estimativas modernas para eucariotos são faixas, frequentemente cerca de 30–32 ATP por glicose, não um número universal fixo.", "Toda célula não produz exatamente 36 ou 38 ATP por glicose.", "molecular"],
  ["Respiração × Fotossíntese", "cycle", "Fotossíntese armazena energia e reduz carbono; respiração libera energia química ao oxidar moléculas orgânicas.", "Como luz e atividade respiratória alteram a troca líquida de gases de uma planta?", "Intensidade luminosa", "Demanda respiratória", "Troca líquida de CO₂", "Plantas realizam ambos os processos; o balanço líquido depende de tecido, luz, temperatura e estado fisiológico.", "Fotossíntese não é a respiração das plantas ao contrário em todos os detalhes.", "plant"],
  ["Fábrica de ATP", "energy", "ATP sintase usa o fluxo de prótons para acoplar ADP e fosfato.", "Como gradiente de prótons e disponibilidade de ADP alteram a síntese?", "Força próton-motriz", "ADP disponível", "ATP sintetizado", "A ATP sintase é uma máquina molecular reversível; sem gradiente ou ADP, a produção desacelera.", "A enzima não cria energia: converte a energia eletroquímica do gradiente.", "molecular"],
];

export const simContent = Object.fromEntries(simRows.map(([title, mechanic, phenomenon, question, controlA, controlB, output, concept, misconception, source]) => [title, {
  mechanic, phenomenon, question, controlA, controlB, output, concept, misconception, source: scientificSources[source],
}])) as Record<string, SimContent>;

export type QuestStage = {
  id: string;
  phase: string;
  kind: "case" | "retrieval" | "hypothesis" | "evidence" | "selection" | "surprise" | "revision" | "formalization" | "transfer";
  title: string;
  body: string;
  prompt?: string;
  options?: Array<{ text: string; correct: boolean; feedback: string }>;
  evidence?: Array<{ text: string; relevant?: boolean; strength?: "strong" | "moderate" | "ambiguous" | "weak"; feedback?: string }>;
  teacherNote?: string;
};

export type QuestContent = {
  caseText: string;
  question: string;
  evidence: Array<{ text: string; relevant: boolean }>;
  hypotheses: Array<{ text: string; correct: boolean; feedback: string }>;
  concept: string;
  misconception: string;
  source: ScientificSource;
  stages?: QuestStage[];
  transfer?: string;
  duration?: string;
  gradeBand?: string;
  mode?: string;
};

type QuestRow = [string, string, string, string, string, string, string, string, string, string, string];
const questRows: QuestRow[] = [
  ["Resistência bacteriana", "Após vários ciclos de antibiótico, uma população bacteriana volta a crescer.", "Qual explicação é sustentada pelos dados de sobrevivência?", "Antes do antibiótico havia poucas colônias resistentes.", "O antibiótico elimina sobretudo as bactérias suscetíveis.", "As sobreviventes deixam mais descendentes resistentes.", "O corpo do paciente se acostumou ao antibiótico.", "O antibiótico selecionou variantes bacterianas resistentes já presentes ou recém-originadas.", "Pressão seletiva muda a frequência de resistência; genes também podem se espalhar horizontalmente.", "Quem se torna resistente é a bactéria, não a pessoa.", "microbiology"],
  ["Crescimento bacteriano", "Uma cultura cresce, estabiliza e depois perde células viáveis em um frasco fechado.", "Que evidências distinguem limitação de nutrientes de falta de reprodução?", "A contagem cresce exponencialmente no início.", "Nutrientes caem e resíduos se acumulam antes do platô.", "Ao transferir células para meio novo, o crescimento recomeça.", "Bactérias param porque decidem não se dividir.", "O platô resulta do balanço entre divisão e morte sob recursos limitados.", "Culturas fechadas passam por fases lag, exponencial, estacionária e declínio.", "A fase estacionária não significa que todas as células estejam inativas.", "microbiology"],
  ["Ciclo de vida de um vírus", "Células expostas a partículas virais passam a produzir novas partículas.", "Qual sequência explica a dependência do vírus em relação à célula hospedeira?", "Partículas se ligam a receptores específicos da célula.", "O genoma viral é copiado usando componentes celulares e virais.", "Novas partículas são montadas e liberadas.", "O vírus cresce sozinho consumindo nutrientes do meio.", "Ligação, entrada, replicação, montagem e saída formam um ciclo dependente da célula.", "Vírus usam células para produzir componentes e podem ter ciclos e estratégias diversos.", "Vírus não são pequenas bactérias e antibióticos não bloqueiam seu ciclo.", "microbiology"],
  ["História de uma bactéria", "Uma bactéria intestinal encontra ambientes com pH, nutrientes e competidores diferentes.", "Quais evidências explicam por que ela prospera em um local e não em outro?", "Seu crescimento muda quando a fonte de carbono é trocada.", "A microbiota vizinha compete por espaço e nutrientes.", "Genes são ativados conforme sinais do ambiente.", "Toda bactéria causa doença sempre que entra no corpo.", "A mesma bactéria responde plasticamente ao ambiente e interage com uma comunidade.", "Bactérias ocupam nichos, regulam genes e muitas vivem em relações neutras ou benéficas.", "Bactéria não é sinônimo de patógeno.", "microbiology"],
  ["Surto na escola", "Em uma escola, estudantes de turmas diferentes apresentam sintomas gastrointestinais ao longo de dois dias.", "O padrão aponta para uma fonte comum, transmissão entre pessoas ou mais de um processo?", "Os primeiros casos ocorreram após uma atividade coletiva.", "Casos secundários aparecem depois entre contatos próximos.", "A curva temporal é compatível com propagação.", "Todos os casos vieram do alimento do primeiro dia.", "O padrão combina exposição inicial e transmissão posterior; é preciso comparar contatos e fontes.", "Investigar um surto exige comparar tempo, turma, exposição, contatos e amostras.", "Correlação temporal não prova uma fonte única.", "inquiry"],
  ["O alimento contaminado", "Várias pessoas adoecem depois de uma refeição. Nem todos comeram os mesmos itens.", "Como investigar a origem sem confundir coincidência com causa?", "A curva de sintomas se concentra após a refeição.", "O item suspeito foi consumido por quase todos os doentes.", "O mesmo agente aparece em pacientes e na amostra do item.", "O último alimento servido foi necessariamente a causa.", "A hipótese mais forte combina exposição comum, temporalidade e evidência laboratorial.", "Surtos exigem comparar exposições, tempo, amostras e fontes alternativas.", "A aparência do alimento não prova contaminação.", "microbiology"],
  ["O antibiótico que deixou de funcionar", "Um antibiótico controlava uma infecção, mas a nova cultura mostra crescimento na mesma dose.", "O que precisa ser testado antes de concluir que o medicamento falhou?", "A concentração inibitória mínima aumentou.", "A linhagem recuperada tem perfil semelhante.", "A dose foi tomada de forma irregular.", "O paciente criou resistência ao antibiótico.", "A falha deve ser investigada com teste de sensibilidade e dados de exposição.", "Resistência, adesão, dose, biofilme e reinfecção podem produzir falha aparente.", "Uma piora isolada não prova resistência.", "microbiology"],
  ["CSI Biologia — morte dos peixes", "Peixes aparecem mortos em um lago depois de mudança na cor da água e de uma chuva intensa.", "Qual cadeia de eventos conecta a mudança do lago à mortalidade?", "O oxigênio dissolvido cai antes do amanhecer.", "Nutrientes aumentam após o escoamento da chuva.", "A mortalidade se concentra onde há mais matéria orgânica.", "A chuva matou os peixes diretamente.", "Nutrientes, algas, decomposição e queda de oxigênio formam uma explicação plausível.", "Eutrofização conecta nutrientes, algas, decomposição e hipóxia.", "Água verde não prova sozinha a causa.", "ecology"],
  ["Extinção — a rã-do-brejo", "Uma população de rãs diminui em uma área úmida onde a água ainda parece presente.", "Como separar perda de habitat, doença e efeito de predadores?", "A área alagada seca antes da reprodução.", "Indivíduos apresentam lesões compatíveis com doença.", "Fragmentos vizinhos não têm conexão.", "A espécie desapareceu apenas porque há predadores.", "A queda combina habitat, risco sanitário e isolamento.", "Extinção local resulta da interação entre habitat, doenças, predadores e conectividade.", "Encontrar água não garante habitat adequado.", "ecology"],
  ["Crime ambiental — quem matou o rio?", "Um rio recebe uma descarga irregular e depois apresenta espuma, odor e redução de invertebrados.", "Como atribuir a causa sem confundir presença de poluente com efeito?", "A concentração aumenta a jusante da descarga.", "A comunidade de invertebrados muda em um gradiente.", "A substância aparece na amostra da tubulação.", "Qualquer substância encontrada é automaticamente a causa.", "Fonte, gradiente espacial, tempo e resposta biológica convergem.", "Diagnóstico ambiental combina fonte, trajetória, concentração, tempo e indicadores.", "Presença de substância não prova todo o impacto.", "ecology"],
  ["Fazenda — por que plantas estão morrendo?", "Plantas da mesma variedade murcham em uma faixa da fazenda, embora o solo pareça úmido.", "Que variável pode estar impedindo a absorção de água?", "A condutividade elétrica do solo é maior.", "Raízes apresentam danos nas pontas.", "Irrigação aumenta a umidade sem recuperar o turgor.", "Basta adicionar mais água.", "Salinidade e dano radicular reduzem a entrada de água mesmo com solo úmido.", "Água disponível não é o mesmo que água absorvível.", "Murcha não prova falta de água.", "plant"],
  ["Hospital — qual sistema está afetado?", "Uma pessoa apresenta respiração acelerada, cansaço e alteração ácido-base após uma infecção.", "Como ventilação, troca gasosa e circulação localizam o problema?", "A saturação arterial está baixa apesar da ventilação aumentada.", "A imagem mostra regiões com líquido.", "A perfusão é desigual.", "Respirar rápido significa que o coração é a causa.", "Ventilação, difusão e perfusão precisam ser comparadas.", "Sintomas semelhantes podem surgir por falhas diferentes no sistema respiratório.", "Respirar mais não garante mais oxigênio nos tecidos.", "physiology"],
  ["Zoológico — por que animais mudaram comportamento?", "Animais passam a se esconder e reduzir a alimentação após uma reforma próxima.", "Como investigar estresse ambiental sem atribuir o comportamento a uma causa única?", "A alteração começou após aumento de ruído e vibração.", "O padrão diminui com abrigo e som previsível.", "Espécies diferentes respondem de modos distintos.", "Os animais ficaram tristes por causa da reforma.", "A hipótese fica mais forte com estímulo, resposta e intervenção controlada.", "Comportamento emerge da interação entre estímulos, necessidades e ambiente.", "Mudança de comportamento não revela sozinha a causa.", "inquiry"],
  ["E se a Terra parasse de girar?", "Um modelo reduz gradualmente a rotação terrestre, mantendo massa e órbita constantes.", "Quais consequências decorrem diretamente da perda de rotação e quais são especulação?", "O ciclo dia-noite tenderia a acompanhar o ano orbital.", "A circulação atmosférica perderia grande parte do efeito de Coriolis.", "A redistribuição dos oceanos e da atmosfera seria extrema e lenta.", "A gravidade desapareceria imediatamente em toda a superfície.", "A rotação afeta ciclos de iluminação, circulação e forma do planeta, mas não é a fonte principal da gravidade.", "Reduzir a rotação reorganiza iluminação e circulação sem eliminar a atração gravitacional da massa terrestre.", "Sem rotação, a Terra ainda teria gravidade devido à sua massa.", "nasa"],
  ["E se a gravidade fosse menor?", "Um planeta com a mesma atmosfera e raio recebe uma gravidade superficial reduzida no modelo.", "Que mudanças são consequências plausíveis de menor aceleração gravitacional?", "Objetos teriam menor peso, mas a mesma massa.", "Saltos e trajetórias balísticas durariam mais.", "Reter gases leves na atmosfera seria mais difícil ao longo do tempo.", "Todos os organismos cresceriam gigantes instantaneamente.", "Gravidade influencia movimento, circulação e retenção atmosférica; respostas biológicas dependeriam de muitas gerações.", "Menor gravidade muda peso e trajetórias de imediato, mas mudanças biológicas dependem de fisiologia e evolução.", "Massa e peso não são a mesma grandeza.", "nasa"],
  ["E se não existissem bactérias?", "Um cenário remove todas as bactérias de ecossistemas, organismos e ciclos biogeoquímicos.", "Quais evidências mostram que o efeito não seria apenas o fim de doenças bacterianas?", "Decomposição e reciclagem de nutrientes cairiam drasticamente.", "Fixação de nitrogênio e microbiomas seriam interrompidos.", "Muitas cadeias alimentares e relações simbióticas perderiam funções essenciais.", "A vida ficaria automaticamente mais saudável sem germes.", "Bactérias sustentam ciclos, simbioses e produção; uma minoria é patogênica.", "A remoção de bactérias interromperia funções ecológicas e fisiológicas essenciais muito antes de representar apenas menos doenças.", "Microrganismos não são apenas agentes de doença.", "microbiology"],
  ["E se o oxigênio dobrasse?", "A fração de O₂ atmosférico é elevada, mantendo inicialmente os demais fatores constantes.", "Que efeitos decorrem do maior O₂ e quais dependem de adaptação e tempo?", "Materiais combustíveis inflamariam com mais facilidade.", "Espécies reativas de oxigênio imporiam maior estresse oxidativo.", "Difusão não garantiria desempenho humano dobrado porque outros sistemas limitam.", "Humanos teriam imediatamente o dobro da energia.", "O₂ sustenta respiração e combustão, mas excesso aumenta riscos e não remove outros fatores limitantes.", "O excesso de O₂ modifica combustão e estresse oxidativo, sem duplicar automaticamente o metabolismo.", "Mais oxigênio não implica produção de ATP proporcional sem combustível, enzimas e demanda.", "nasa"],
  ["E se as plantas desaparecessem?", "Um modelo remove plantas terrestres, mas acompanha efeitos em tempos diferentes.", "Qual sequência de evidências conecta plantas a alimento, carbono, água e habitats?", "A produção primária terrestre e muitas cadeias alimentares colapsariam primeiro.", "Transpiração, solo e microclimas mudariam rapidamente.", "O₂ atmosférico cairia mais lentamente que alimentos e habitats, devido ao grande reservatório.", "O oxigênio acabaria em poucas horas.", "Plantas sustentam produção primária, estrutura de habitats e ciclos; efeitos têm escalas temporais distintas.", "Alimento, habitat e ciclos de água e carbono entrariam em crise antes de um esgotamento rápido do reservatório global de O₂.", "A primeira crise não seria necessariamente a falta imediata de O₂.", "ecology"],
];

export const questContent = Object.fromEntries(questRows.map(([title, caseText, question, e1, e2, e3, wrong, correct, concept, misconception, source]) => [title, {
  caseText, question,
  evidence: [{ text: e1, relevant: true }, { text: e2, relevant: true }, { text: e3, relevant: true }, { text: wrong, relevant: false }],
  hypotheses: [
    { text: correct, correct: true, feedback: `Boa conclusão. ${concept}` },
    { text: wrong, correct: false, feedback: `Essa hipótese confunde causa e evidência. ${misconception}` },
  ], concept, misconception, source: scientificSources[source],
}])) as Record<string, QuestContent>;

export type StoryContent = {
  role: string;
  question: string;
  steps: Array<{ title: string; body: string }>;
  concept: string;
  source: ScientificSource;
};

type StoryRow = [string, string, string, string, string, string, string, string, string, string, string];
const storyRows: StoryRow[] = [
  ["Viagem de uma molécula de água", "Você acompanha uma molécula, sem supor um caminho único.", "Que processos podem mudar seu estado e reservatório?", "Evaporação", "A energia solar favorece a passagem para vapor na superfície.", "Condensação", "O resfriamento permite a formação de gotículas em nuvens.", "Precipitação e caminhos", "Após cair, a molécula pode infiltrar, escoar, congelar ou ser incorporada por seres vivos.", "O ciclo da água é uma rede de trajetos com tempos de residência diferentes.", "nasa"],
  ["Viagem de uma molécula de oxigênio", "Você segue O₂ desde um alvéolo até uma mitocôndria.", "Quais gradientes e transportadores tornam a entrega possível?", "Alvéolo", "O₂ difunde através da barreira alvéolo-capilar seguindo pressão parcial.", "Hemácia", "A hemoglobina liga O₂ reversivelmente e amplia a capacidade de transporte.", "Tecido e mitocôndria", "O₂ deixa o sangue onde a pressão é menor e recebe elétrons no fim da cadeia respiratória.", "Ventilação, difusão, circulação e metabolismo formam uma cadeia causal.", "physiology"],
  ["Viagem de um nutriente pelo organismo", "Você acompanha um aminoácido de uma refeição até uma célula.", "Que transformações separam digestão, absorção e uso metabólico?", "Digestão", "Proteases liberam peptídeos e aminoácidos no tubo digestório.", "Absorção e fígado", "Transportadores levam aminoácidos ao sangue portal e o fígado regula seu destino.", "Célula-alvo", "O aminoácido pode entrar em proteínas, sinais ou metabolismo energético.", "Nutrientes são moléculas processadas e distribuídas, não pedaços de alimento circulando.", "physiology"],
  ["Encolhido ao tamanho de um vírus", "Você tem cerca de 100 nm e observa uma partícula viral próxima a uma célula.", "O que a escala permite ver sobre estrutura e dependência?", "Superfície viral", "Proteínas de ligação reconhecem receptores; não há órgãos ou movimento intencional.", "Entrada", "Membranas se fundem ou a célula internaliza a partícula, conforme o vírus.", "Produção de cópias", "Genoma e proteínas são produzidos usando a maquinaria da célula hospedeira.", "A escala evidencia que vírus são sistemas moleculares dependentes de células.", "microbiology"],
  ["Dentro do núcleo", "Você entra no núcleo durante a intérfase.", "Como dois metros de DNA ficam organizados e acessíveis?", "Territórios cromossômicos", "Cada cromossomo ocupa regiões dinâmicas, sem virar um novelo aleatório.", "Gene ativo", "Cromatina mais acessível recruta fatores e RNA polimerase.", "Poros nucleares", "RNAs e proteínas atravessam complexos de poro de modo regulado.", "O núcleo organiza armazenamento, expressão e tráfego de informação genética.", "molecular"],
  ["Viagem dentro de uma hemácia", "Você observa uma hemácia humana madura por dentro.", "Por que ela transporta gases com eficiência e tem vida limitada?", "Forma bicôncava", "Grande relação superfície-volume e flexibilidade favorecem trocas e passagem capilar.", "Hemoglobina", "Milhões de moléculas ligam O₂ conforme o ambiente químico.", "Sem núcleo e mitocôndrias", "Mais espaço para hemoglobina, mas pouca capacidade de reparo e nenhuma respiração aeróbia própria.", "Estrutura, metabolismo e função da hemácia estão intimamente relacionados.", "physiology"],
  ["Viajando pelo sangue", "Você percorre circulação pulmonar e sistêmica com o plasma.", "Como pressão, válvulas e diâmetro dos vasos organizam o fluxo?", "Coração", "Diferenças de pressão impulsionam sangue e válvulas evitam refluxo.", "Artérias e capilares", "Ramificações distribuem fluxo; capilares oferecem grande área de troca.", "Veias", "Baixa pressão, válvulas e bomba muscular ajudam o retorno ao coração.", "O sistema circulatório é um circuito contínuo guiado por gradientes de pressão.", "physiology"],
  ["Você é um anticorpo", "Você acompanha uma imunoglobulina secretada por um plasmócito.", "O que significa reconhecer especificamente um antígeno?", "Encontro molecular", "Regiões variáveis ligam certos epítopos por complementaridade química.", "Efeito", "A ligação pode neutralizar ou marcar o alvo para outros mecanismos.", "Memória", "Clones de células B de memória permitem resposta posterior mais rápida.", "Anticorpos reconhecem epítopos e cooperam com células e complemento; não 'matam tudo' sozinhos.", "immunity"],
  ["Corrida de um espermatozoide", "Você segue um dos muitos espermatozoides no trato reprodutivo.", "Quais filtros biológicos tornam fecundação diferente de uma simples corrida?", "Capacitação", "Mudanças de membrana tornam possível responder ao entorno do ovócito.", "Barreiras e sinais", "Muco, contrações, geometria e sinais químicos influenciam trajetórias.", "Fecundação", "Interações específicas permitem fusão; bloqueios reduzem polispermia.", "Fecundação resulta de seleção, transporte e reconhecimento celular, não apenas do mais veloz.", "physiology"],
  ["Você é um neurônio", "Você acompanha informação de dendritos ao terminal axonal.", "Como sinais graduados tornam-se potenciais de ação e comunicação sináptica?", "Integração", "Potenciais excitatórios e inibitórios somam-se no tempo e no espaço.", "Axônio", "Acima do limiar, potenciais de ação propagam-se sem diminuir de amplitude.", "Sinapse", "Ca²⁺ desencadeia liberação de neurotransmissor, que altera a célula seguinte.", "Neurônios transformam sinais entre formas elétricas e químicas em redes.", "physiology"],
  ["Você é uma bactéria resistente", "Você acompanha uma bactéria com um gene de resistência antes e depois do antibiótico.", "A resistência surgiu porque o antibiótico pediu uma adaptação?", "Antes da exposição", "A variante resistente já pode existir por mutação ou transferência genética.", "Durante o antibiótico", "Suscetíveis diminuem e resistentes deixam proporção maior de descendentes.", "Depois", "Genes de resistência podem se espalhar vertical ou horizontalmente.", "O ambiente seleciona variantes; não produz intencionalmente a mutação necessária.", "microbiology"],
  ["Você é uma planta", "Você acompanha carbono, água e sinais em um organismo fixo e responsivo.", "Como raízes e folhas coordenam recursos em ambientes variáveis?", "Raiz", "Água e minerais entram e sinais ajustam arquitetura e estômatos.", "Folha", "CO₂ entra pelos estômatos e luz sustenta reações fotossintéticas.", "Transporte", "Xilema e floema conectam fontes, drenos e regiões de crescimento.", "Plantas percebem, sinalizam e ajustam crescimento sem sistema nervoso.", "plant"],
  ["Viagem de um fóton", "Você segue um fóton do Sol até um fotossistema e além.", "Quando sua energia é refletida, dissipada ou capturada?", "Chegada à folha", "Pigmentos absorvem certos comprimentos de onda e refletem outros.", "Excitação", "A energia eleva elétrons e pode ser transferida ao centro de reação.", "Conversão", "O fluxo eletrônico ajuda a formar ATP e NADPH; nem toda energia incidente é capturada.", "Fotossíntese converte parte da energia luminosa em energia química por etapas.", "plant"],
];

export const storyContent = Object.fromEntries(storyRows.map(([title, role, question, t1, b1, t2, b2, t3, b3, concept, source]) => [title, {
  role, question, steps: [{ title: t1, body: b1 }, { title: t2, body: b2 }, { title: t3, body: b3 }], concept, source: scientificSources[source],
}])) as Record<string, StoryContent>;

export type ChallengeContent = {
  mission: string;
  question: string;
  actions: Array<{ label: string; effect: number; explanation: string }>;
  success: string;
  concept: string;
  source: ScientificSource;
};

type ChallengeRow = [string, string, string, string, string, string, string, string, string, string, string];
const challengeRows: ChallengeRow[] = [
  ["Corrida das enzimas", "Otimize uma reação sem desnaturar a enzima nem saturar o sistema.", "Qual combinação aumenta a taxa dentro de limites biológicos?", "Aumentar substrato", "Eleva a taxa até a saturação dos sítios ativos.", "Aproximar do pH ótimo", "Preserva cargas e forma do sítio ativo.", "Aquecer acima do ótimo", "Pode desnaturar e reduzir a atividade.", "Você distinguiu aumento de colisões, saturação e desnaturação.", "chemistry"],
  ["O DNA compactando", "Compacte uma molécula de DNA sem impedir totalmente o acesso aos genes.", "Como equilibrar armazenamento e acessibilidade?", "Adicionar nucleossomos", "Organiza o DNA e reduz o espaço ocupado.", "Abrir região ativa", "Permite recrutamento da maquinaria de transcrição.", "Condensar tudo", "Protege, mas bloqueia expressão e replicação.", "Cromatina é compacta e dinâmica; acessibilidade é regulada localmente.", "molecular"],
  ["Ligando e desligando genes", "Faça uma célula responder a um sinal ativando apenas o gene-alvo.", "Quais elementos garantem resposta específica e reversível?", "Ativar fator de transcrição", "Conecta o sinal a sequências regulatórias.", "Abrir cromatina-alvo", "Aumenta acesso da maquinaria ao gene correto.", "Ativar todos os promotores", "Causa expressão indiscriminada e perde especificidade.", "Regulação combina sinais, fatores, cromatina e regiões regulatórias.", "molecular"],
  ["Engenharia genética", "Produza uma proteína humana em bactéria com um desenho experimental controlado.", "Que construção permite expressão e verificação?", "Usar cDNA e promotor bacteriano", "Remove íntrons e fornece sinal de transcrição compatível.", "Incluir marcador e controle", "Permite selecionar transformadas e comparar resultados.", "Inserir gene genômico sem planejamento", "Íntrons e regulação incompatível podem impedir expressão.", "Engenharia genética exige compatibilidade entre sequência, vetor, hospedeiro e teste.", "genetics"],
  ["CRISPR", "Edite um sítio específico minimizando cortes fora do alvo.", "Como escolher guia, nuclease e forma de reparo?", "Escolher guia específico", "Direciona Cas ao alvo complementar próximo de PAM.", "Fornecer molde de reparo", "Pode orientar uma alteração precisa quando a célula o utiliza.", "Ignorar sítios semelhantes", "Aumenta risco de edições fora do alvo.", "CRISPR combina reconhecimento por RNA, corte/edição e reparo celular; precisão requer validação.", "genetics"],
  ["Competição entre plantas", "Mantenha duas espécies em um canteiro com luz, água e nutrientes limitados.", "Qual manejo reduz exclusão competitiva?", "Diversificar profundidade de raízes", "Separa parcialmente o uso de recursos do solo.", "Ajustar densidade", "Reduz sobreposição intensa por luz e nutrientes.", "Aumentar uma espécie sem limite", "Amplia competição e pode excluir a outra.", "Nicho, densidade e heterogeneidade determinam coexistência, não uma força competitiva universal.", "plant"],
  ["Crescimento de raízes", "Direcione raízes para água e nutrientes sem bloquear oxigenação.", "Que sinais alteram arquitetura radicular?", "Criar gradiente de umidade", "Favorece crescimento e ramificação em zonas úteis.", "Manter solo aerado", "Sustenta respiração das células da raiz.", "Encharcar continuamente", "Reduz O₂ e pode inibir crescimento.", "Raízes integram gravidade, água, nutrientes, oxigênio e hormônios.", "plant"],
  ["Fototropismo", "Faça o caule alcançar luz lateral mantendo crescimento saudável.", "Como luz azul e auxina produzem curvatura?", "Iluminar lateralmente", "Fototropinas iniciam redistribuição de sinais.", "Permitir transporte de auxina", "Maior alongamento no lado sombreado curva o caule.", "Bloquear o ápice", "Impede percepção eficiente do sinal direcional.", "Curvatura resulta de crescimento diferencial, não de a planta se deslocar.", "plant"],
  ["Hormônios vegetais", "Coordene germinação, alongamento e resposta à seca com sinais adequados.", "Qual hormônio é coerente com cada contexto?", "Elevar giberelina na semente", "Favorece mobilização de reservas e germinação.", "Elevar ABA na seca", "Favorece fechamento estomático e respostas de tolerância.", "Usar auxina para tudo", "Hormônios interagem e têm efeitos dependentes do tecido e dose.", "Hormônios vegetais formam redes contextuais, não botões de uma única função.", "plant"],
  ["Dispersão de sementes", "Maximize colonização sem perder todas as sementes longe de habitats adequados.", "Como combinar distância e estabelecimento?", "Adicionar estruturas aladas", "Aumenta transporte pelo vento em certas condições.", "Atrair dispersores animais", "Pode levar sementes a locais e distâncias variados.", "Maximizar distância apenas", "Distância sem habitat adequado reduz recrutamento.", "Dispersão tem compromisso entre transporte, chegada e germinação.", "plant"],
  ["Guerra microscópica", "Controle uma infecção sem causar dano inflamatório excessivo ao tecido.", "Como coordenar resposta inata e adaptativa?", "Conter rapidamente com resposta inata", "Limita expansão e fornece sinais iniciais.", "Ativar resposta específica", "Células T e B ampliam controle e memória.", "Manter inflamação máxima", "Pode lesar o próprio tecido.", "Imunidade eficaz equilibra eliminação do patógeno e controle do dano.", "immunity"],
  ["Anticorpos", "Neutralize um vírus e sinalize partículas restantes para remoção.", "Que propriedades tornam um anticorpo eficaz?", "Aumentar afinidade específica", "Melhora ligação ao epítopo correto.", "Recrutar células e complemento", "A região constante conecta reconhecimento a mecanismos efetores.", "Ligar qualquer molécula", "Perde especificidade e aumenta dano colateral.", "Anticorpos reconhecem epítopos e atuam por neutralização e recrutamento de outros mecanismos.", "immunity"],
  ["Vacinação", "Construa memória imunológica com baixo risco e boa cobertura populacional.", "Que estratégia reduz doença e transmissão?", "Apresentar antígeno com esquema adequado", "Induz resposta e memória sem a doença-alvo completa.", "Ampliar cobertura e reforços indicados", "Reduz suscetíveis e sustenta proteção.", "Esperar infecção natural", "Impõe risco de doença, complicações e transmissão.", "Vacinas treinam a resposta adaptativa; proteção depende de produto, esquema, pessoa e circulação do agente.", "immunity"],
  ["HIV", "Reduza a produção de HIV bloqueando etapas complementares do ciclo viral.", "Por que combinar antirretrovirais?", "Bloquear transcriptase reversa", "Dificulta conversão do RNA viral em DNA.", "Bloquear integrase ou protease", "Interrompe outra etapa e reduz cópias funcionais.", "Usar uma única barreira irregularmente", "Favorece seleção de variantes resistentes.", "Terapia combinada suprime replicação ao atingir etapas diferentes e protege células CD4.", "hiv"],
  ["Infarto", "Restaure perfusão de um território cardíaco antes que a isquemia cause dano extenso.", "Qual sequência liga obstrução coronariana ao músculo lesionado?", "Reconhecer obstrução e agir cedo", "Menor tempo de isquemia preserva mais miocárdio.", "Restabelecer fluxo", "Reperfusão devolve O₂ e substratos ao tecido viável.", "Aumentar apenas a frequência cardíaca", "Eleva demanda de O₂ sem remover a obstrução.", "Infarto geralmente envolve interrupção do fluxo coronariano e perda de tecido dependente do tempo.", "physiology"],
  ["Pressão arterial", "Mantenha perfusão sem sobrecarregar vasos usando débito e resistência.", "Como calibre arteriolar e débito afetam a pressão?", "Ajustar resistência arteriolar", "Vasoconstrição tende a elevar resistência periférica.", "Ajustar débito cardíaco", "Frequência e volume sistólico alteram fluxo por minuto.", "Confundir pressão com quantidade de sangue", "Pressão emerge de fluxo, resistência, volume e elasticidade.", "Regulação combina coração, vasos, rins e sistema nervoso ao longo de escalas diferentes.", "physiology"],
  ["Asma", "Recupere o fluxo de ar em vias inflamadas e estreitadas.", "Qual intervenção atua sobre broncoconstrição e qual sobre inflamação?", "Broncodilatar", "Aumenta o calibre e reduz resistência rapidamente.", "Controlar inflamação", "Reduz hiperreatividade e risco de novas crises.", "Forçar mais ar sem tratar o estreitamento", "Pode aumentar esforço sem corrigir a causa.", "Asma envolve inflamação variável, hiperresponsividade e limitação reversível do fluxo.", "physiology"],
  ["Troca gasosa", "Mantenha O₂ e CO₂ adequados através de ventilação, perfusão e difusão.", "O que acontece quando alvéolo ventilado não recebe sangue?", "Combinar ventilação e perfusão", "Aproxima ar e sangue para trocas eficientes.", "Preservar área e espessura da barreira", "Favorece difusão rápida.", "Aumentar ventilação isoladamente", "Não corrige regiões sem perfusão adequada.", "A eficiência depende da correspondência ventilação-perfusão e do gradiente através de barreira fina.", "physiology"],
  ["Reflexo", "Produza uma resposta rápida a um estímulo nocivo antes da análise consciente completa.", "Quais elementos fecham o arco reflexo?", "Ativar receptor e neurônio sensorial", "Converte estímulo e leva sinal à medula.", "Integrar e ativar neurônio motor", "Gera resposta muscular rápida.", "Esperar decisão consciente", "Atrasaria a proteção; consciência pode vir depois.", "Arcos reflexos integram receptor, vias aferente/eferente e centro nervoso.", "physiology"],
  ["Memória", "Fortaleça uma lembrança distribuída sem confundir familiaridade com recordação precisa.", "Que práticas favorecem consolidação e recuperação?", "Praticar recuperação espaçada", "Reativação em intervalos fortalece acesso e discriminação.", "Dormir após aprender", "Sono participa da consolidação de diferentes memórias.", "Reler passivamente muitas vezes", "Aumenta familiaridade, mas pode gerar ilusão de domínio.", "Memória é reconstruída por redes; codificação, consolidação e recuperação podem falhar de modos distintos.", "physiology"],
  ["Ponto cego", "Revele a região sem fotorreceptores onde o nervo óptico deixa a retina.", "Por que normalmente não vemos um buraco no campo visual?", "Alinhar o alvo com o disco óptico", "Faz a imagem cair na região sem cones ou bastonetes.", "Comparar visão mono e binocular", "O outro olho e o contexto visual podem preencher informação.", "Procurar uma mancha preta fixa", "O cérebro interpola padrões, então o ponto não aparece como mancha.", "O ponto cego é ausência de amostragem retinal compensada por sobreposição e inferência.", "physiology"],
  ["Localização do som", "Localize uma fonte usando diferenças entre os dois ouvidos.", "Que pistas dominam em frequências diferentes?", "Comparar tempo de chegada", "Diferenças interaurais de tempo ajudam sobretudo em sons graves.", "Comparar intensidade e espectro", "Cabeça e orelhas produzem pistas úteis, especialmente em altas frequências e elevação.", "Usar um ouvido sem mover a cabeça", "Remove muitas pistas espaciais.", "O cérebro integra tempo, nível e filtragem do pavilhão para estimar direção.", "physiology"],
  ["Deriva continental", "Reconstrua a separação dos continentes usando linhas independentes de evidência.", "Quais dados sustentam movimento ao longo do tempo?", "Unir fósseis e rochas correlatas", "Distribuições hoje separadas indicam continuidade antiga.", "Usar faixas magnéticas oceânicas", "Registra expansão simétrica do assoalho oceânico.", "Apoiar-se apenas no encaixe visual", "É sugestivo, mas insuficiente sem outras evidências.", "Deriva continental ganhou mecanismo com tectônica de placas e expansão oceânica.", "earth"],
  ["Formação de fósseis", "Preserve restos ou vestígios antes que decomposição e erosão os destruam.", "Quais condições aumentam a chance de fossilização?", "Soterrar rapidamente", "Reduz exposição a necrófagos, oxigênio e intemperismo.", "Favorecer partes resistentes e minerais", "Aumenta chance de moldes, substituição ou permineralização.", "Deixar exposto na superfície", "Acelera decomposição e destruição.", "O registro fóssil é enviesado por ambiente, organismo e processos geológicos.", "earth"],
  ["Ciclo das rochas", "Transforme uma rocha por processos geológicos sem supor uma rota obrigatória.", "Que condições levam a ígnea, sedimentar ou metamórfica?", "Fundir e resfriar", "Magma solidificado forma rocha ígnea.", "Compactar sedimentos ou metamorfizar", "Soterramento gera caminhos distintos conforme temperatura e pressão.", "Seguir sempre um círculo fixo", "Rochas podem pular etapas e percorrer rotas variadas.", "O ciclo das rochas é uma rede de transformações movida por energia interna e processos superficiais.", "earth"],
  ["Camadas da Terra", "Associe evidências sísmicas às propriedades de crosta, manto e núcleo.", "Como ondas revelam regiões que não podemos acessar?", "Comparar ondas P e S", "Ondas S não atravessam o núcleo externo líquido; P mudam velocidade e direção.", "Usar densidade e campo magnético", "Restringe composição e estado das camadas profundas.", "Imaginar camadas homogêneas e imóveis", "Ignora convecção, transições e heterogeneidade.", "Camadas composicionais e mecânicas são inferidas por múltiplas evidências geofísicas.", "earth"],
  ["Salve a floresta", "Priorize ações que mantenham biodiversidade, conectividade e serviços ecossistêmicos.", "Qual portfólio enfrenta causas e não só sintomas?", "Proteger áreas e corredores", "Reduz perda de habitat e conecta populações.", "Apoiar uso sustentável e fiscalização", "Alinha conservação com condições sociais e reduz pressão.", "Plantar uma única espécie em toda área", "Cria cobertura, mas não restaura a complexidade da floresta.", "Conservação exige proteger processos, diversidade e pessoas em várias escalas.", "ecology"],
  ["Controle uma epidemia", "Reduza transmissão protegendo pessoas sem confundir correlação com intervenção eficaz.", "Que combinação diminui o número efetivo de reprodução?", "Identificar casos e reduzir contatos infecciosos", "Interrompe cadeias de transmissão.", "Vacinar quando disponível", "Reduz suscetibilidade e doença conforme a vacina.", "Tratar antibiótico como antiviral universal", "Não atua sobre vírus e pode selecionar resistência bacteriana.", "Controle combina vigilância, prevenção, comunicação e intervenções específicas ao agente.", "microbiology"],
  ["Equilibre um aquário", "Mantenha peixes, plantas e decompositores com oxigênio e nitrogênio em faixas seguras.", "Como alimentação e filtragem biológica afetam o sistema?", "Reduzir excesso de alimento", "Diminui resíduos, amônia e demanda de oxigênio.", "Manter ciclagem microbiana", "Converte compostos nitrogenados em formas menos tóxicas.", "Adicionar muitos peixes", "Aumenta carga orgânica além da capacidade do sistema.", "Aquários dependem de fluxo de energia, ciclagem de nutrientes e trocas gasosas.", "ecology"],
  ["Monte um ecossistema sustentável", "Crie uma rede que mantenha funções sem exigir equilíbrio estático.", "Que propriedades aumentam resiliência?", "Diversificar produtores e interações", "Distribui funções e respostas a perturbações.", "Fechar ciclos de nutrientes", "Decompositores devolvem elementos a formas reutilizáveis.", "Maximizar um único consumidor", "Desbalanceia fluxos e aumenta vulnerabilidade.", "Sustentabilidade envolve diversidade funcional, limites de recursos e capacidade de recuperação.", "ecology"],
  ["Sobreviva à Era Glacial", "Mantenha uma população durante resfriamento e avanço do gelo.", "Que respostas podem ocorrer no indivíduo e nas gerações?", "Migrar para refúgios", "Permite acompanhar habitat adequado sem mudança genética imediata.", "Favorecer variantes tolerantes", "Seleção ao longo de gerações pode alterar frequências herdáveis.", "Escolher adaptar-se instantaneamente", "Indivíduos não comandam mudanças genéticas direcionadas.", "Aclimatação, migração, seleção e extinção operam em escalas distintas.", "evolution"],
  ["Seja Darwin", "Explique adaptação usando variação, herança e reprodução diferencial.", "Qual observação diferencia seleção de esforço individual?", "Medir variação herdável", "Mostra matéria-prima transmitida entre gerações.", "Comparar descendentes produzidos", "Revela sucesso reprodutivo diferencial.", "Afirmar que o uso cria o órgão necessário", "Confunde necessidade com origem da variação.", "Seleção natural é uma explicação populacional baseada em diferenças herdáveis de sucesso.", "evolution"],
  ["Seja Pasteur", "Teste a hipótese de geração espontânea sem impedir a entrada de ar.", "Que desenho separa contaminação por microrganismos do ar em si?", "Usar frasco de pescoço de cisne", "Permite ar, mas retém poeira e microrganismos no pescoço.", "Quebrar ou inclinar como comparação", "Coloca o caldo em contato com partículas retidas.", "Ferver só um frasco aberto", "Não isola a origem da contaminação posterior.", "Controles e previsões rivais tornaram o experimento decisivo.", "inquiry"],
  ["Seja Mendel", "Descubra padrões de herança contando descendentes de cruzamentos planejados.", "Como distinguir dominância de desaparecimento de um alelo?", "Cruzar linhagens e registrar F1", "Mostra uniformidade fenotípica sob dominância completa.", "Autofecundar F1 e contar F2", "Reaparecimento do recessivo revela segregação.", "Analisar poucos descendentes", "Aumenta ruído amostral e pode ocultar proporções.", "Herança particulada e segregação explicam o reaparecimento de fenótipos.", "genetics"],
  ["Seja Fleming", "Investigue uma zona sem bactérias ao redor de um fungo contaminante.", "Que testes sustentam a hipótese de uma substância antibacteriana?", "Comparar com placa sem fungo", "Estabelece crescimento normal como controle.", "Testar filtrado e doses", "Separa efeito de contato e avalia relação dose-resposta.", "Concluir cura universal pela aparência", "Ignora identificação, toxicidade, espectro e reprodução.", "Observação acidental vira ciência por hipótese, controle, repetição e isolamento do fator.", "microbiology"],
  ["Monte sua própria experiência científica", "Crie um teste que permita atribuir uma diferença à variável escolhida.", "O desenho possui hipótese, controle e medida replicável?", "Definir uma variável independente", "Torna clara a comparação causal pretendida.", "Padronizar controles e repetir", "Reduz explicações alternativas e estima variabilidade.", "Mudar vários fatores ao mesmo tempo", "Impede saber qual fator produziu o efeito.", "Uma boa experiência conecta pergunta, previsão, comparação justa, dados e limites da conclusão.", "inquiry"],
];

export const challengeContent = Object.fromEntries(challengeRows.map(([title, mission, question, a1, e1, a2, e2, a3, e3, success, source]) => [title, {
  mission, question,
  actions: [{ label: a1, effect: 18, explanation: e1 }, { label: a2, effect: 14, explanation: e2 }, { label: a3, effect: -16, explanation: e3 }],
  success, concept: success, source: scientificSources[source],
}])) as Record<string, ChallengeContent>;

export type LabContent = {
  scenario: string;
  question: string;
  independent: string;
  levels: string[];
  dependent: string;
  control: string;
  method: string;
  concept: string;
  source: ScientificSource;
};

type LabRow = [string, string, string, string, string, string, string, string, string, string, string];
const labRows: LabRow[] = [
  ["Laboratório de hipóteses", "Sementes idênticas germinam em recipientes com disponibilidades diferentes de água.", "A quantidade de água altera a proporção de sementes que germinam em cinco dias?", "Volume diário de água", "0 mL", "2 mL", "5 mL", "Percentual germinado", "Mesma espécie, lote, temperatura, luz, substrato e tempo; use réplicas e formule previsão antes de medir.", "Uma hipótese precisa ser testável e poder ser contrariada pelos dados.", "inquiry"],
  ["Detetive científico", "Peixes de um tanque reduziram atividade após uma floração de algas.", "A queda de oxigênio dissolvido explica a mudança de comportamento?", "Oxigênio dissolvido", "2 mg/L", "5 mg/L", "8 mg/L", "Movimentos operculares por minuto", "Compare horários e tanques, meça temperatura e não conclua causalidade a partir de uma única coincidência.", "Investigar exige comparar explicações e buscar evidências que as diferenciem.", "inquiry"],
  ["Controle de variáveis", "Discos de folha sobem quando fotossíntese produz gás em solução.", "A intensidade luminosa altera o tempo de subida dos discos?", "Distância da fonte luminosa", "10 cm", "30 cm", "60 cm", "Tempo para 50% dos discos subir", "Mantenha espécie, área dos discos, solução de bicarbonato, temperatura e número de discos; use um controle no escuro.", "Mudar uma variável focal e controlar as demais fortalece a interpretação causal.", "inquiry"],
  ["Gráficos vivos", "Uma cultura de levedura produz CO₂ em temperaturas diferentes durante 20 minutos.", "Qual formato de gráfico revela melhor a mudança da taxa ao longo do tempo?", "Temperatura da cultura", "15 °C", "30 °C", "50 °C", "Volume acumulado de CO₂", "Registre em intervalos iguais, represente tempo no eixo x e compare inclinações sem esconder unidades ou variabilidade.", "Gráficos são modelos dos dados; escolha de eixos, escala e variável altera o que pode ser interpretado.", "inquiry"],
  ["Erros comuns e concepções alternativas", "Uma turma afirma que plantas ganham massa principalmente absorvendo solo.", "Que medida diferencia matéria do solo, água e carbono do ar?", "Disponibilidade de CO₂", "Baixa", "Ambiente", "Elevada", "Ganho de massa seca", "Use plantas equivalentes, acompanhe massa seca e massa do solo, mantenha água e luz e discuta limites antes de revelar o papel do carbono.", "Concepções mudam melhor quando uma previsão explícita entra em conflito produtivo com evidências explicadas.", "inquiry"],
];

export const labContent = Object.fromEntries(labRows.map(([title, scenario, question, independent, l1, l2, l3, dependent, method, concept, source]) => [title, {
  scenario, question, independent, levels: [l1, l2, l3], dependent, control: method, method, concept, source: scientificSources[source],
}])) as Record<string, LabContent>;

export type ActivityContent = SimContent | QuestContent | ChallengeContent | StoryContent | LabContent;

export function contentFor(title: string): ActivityContent | undefined {
  return (detailedBioQuestContent as Partial<Record<string, QuestContent>>)[title]
    ?? (simContent as Partial<Record<string, SimContent>>)[title]
    ?? (questContent as Partial<Record<string, QuestContent>>)[title]
    ?? (challengeContent as Partial<Record<string, ChallengeContent>>)[title]
    ?? (storyContent as Partial<Record<string, StoryContent>>)[title]
    ?? (labContent as Partial<Record<string, LabContent>>)[title];
}
